// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://esvhpkxtpcgfxamffwxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzdmhwa3h0cGNnZnhhbWZmd3hxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4OTA3OTIsImV4cCI6MjA2OTQ2Njc5Mn0.8UGklACFx4LV7Z9Vqnwjm461W2PXqa9YmKt1EKI7WoY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});